### ISSUE TITLE
This app nearly identical to another app!

### ISSUE THREAD

**Issue by aRandomMenno** [Swatian/nexnotes#2]
This note taking app is nearly identical to [this](https://github.com/Kin69/EasyNotes) project!

now I am not saying he stole it, but it is almost a carbon copy but then rewritten in another language. And the author did not give proper credits!

@Kin69
@Swatian

**Comment by mmarif4u** [comment]
Thanks for opening this issue.

I am not new to Android or apps, so if you see a similar thing like this, it could be a coincidence for some parts.

I haven't seen that app before this. While I agree there are few similarities in the UI, it is not stolen or the intention to steal someone work.

To me, both apps are written in different languages with different features and libraries, the similar parts are notes listing UI and settings.

**Comment by mmarif4u** [comment]
I am closing this. If you feel the need to reopen it or want to add anything, please feel free to do so.
