### ISSUE TITLE
Add belarusian translation

### ISSUE THREAD

**Issue by YauheniRusakou** [Swatian/nexnotes#20]

**Comment by mmarif4u** [comment]
Hello, translations are done exclusively through Crowdin. I have added the Belarusian language to the project.

https://crowdin.com/project/nexnotes

**Comment by YauheniRusakou** [comment]
Hello, I translated through Crowdin. Do you see the translation?

**Comment by mmarif4u** [comment]
Hi, yes, I see you have translated a few strings only.
