### ISSUE TITLE
[Feature Request] Nex Notes for PC (Linux)

### ISSUE THREAD

**Issue by Dounial** [Swatian/nexnotes#28]
**Describe the feature**
I love Nex Notes and use it almost everyday but when I'm on my PC I'd love to create Notes there too and haven't found a good application/program because the design of Nex Notes is really appealing to me but I can't seem to find a similar Text-editor in Linux - so <b>I wanted to share my idea, Nex Notes for Linux/PC</b>, maybe even with integration and/or cloud sync? I know it would be a lot of work and even if I have barely knowledge in coding I'd like to help or at least fund the work and project to help contributing. If you like my idea and/or can think you could realize the idea that would be really great! I love the app and a PC-version would be really worth it (in my opinion)

**Additional context**
<b>Maybe a flatpak-version(?)</b> would work as another idea, the flathub has a documentation on how to generate a application with ease, it would be a great start, flatpaks are quiet cross-platform-friendly/compatible and I heard they are easy to develop compared to other application-sources.

**Comment by mmarif4u** [comment]
Thank you for your input regarding the app.

As for your feature request to have the app on Linux or similar platforms, I am also a daily Linux user. When I first envisioned this app, it was inspired by my other projects for Gitea/Forgejo [GitNex](https://gitnex.com/) and [LabNex](https://labnex.app/) for GitLab.

While I would love to create a desktop version for notes, building one is a time-intensive process and would require an API to facilitate communication between the two apps.

That said, let’s see how things develop in the future if time and funding allow.
