### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by Xapitonov** [Swatian/nexnotes#8]
Same crash in all apps version 1.2 / 1.1 / 1.0

and in ZTechDev06/NextNote fork version 1.3. https://github.com/ZTechDev06/NextNote.

Plus also crash when pressing the bell button 🔔 ("Notifications") with no crash message!

![Screenshot_2024-08-09-11-32-30-195_com.swatian.nexnotes.jpg](https://github.com/user-attachments/assets/f53f86e6-7cc0-41ad-8863-40000faa4420)

![Screenshot_2024-08-09-11-32-18-042_com.swatian.nexnotes.jpg](https://github.com/user-attachments/assets/2eb9a7c5-394d-4a11-ac54-3938dcd290f9)

Then you keep the app running 
until you have cleared all the data !

![Screenshot_2024-08-09-12-08-35-367_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/2ab72754-19a0-47f1-87e7-deb43211b7f5)

**Comment by mmarif4u** [comment]
Please provide a stack trace or more info about the crash.

This repository only provides assistance with the source and version released here.

Also there are no notifications in Nex Notes as of now. If it is related to the fork, please consult with the fork owner.

**Comment by mmarif4u** [comment]
Also mention the Android version and device.
