### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Xapitonov** [Swatian/nexnotes#9]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name" translatable="false">Nex Notes</string>
    <string name="patreon" translatable="false">Подержать в Patreon</string>
    <string name="link_patreon" translatable="false">https://www.patreon.com/mmarif</string>
    <string name="buy_me_a_coffee" translatable="false">Услуги перевода Crowdin</string>
    <string name="link_buy_me_a_coffee" translatable="false">https://www.buymeacoffee.com/mmarif</string>
    <string name="app_website_link" translatable="false">https://nexnotes.swatian.com</string>
    <string name="zero" translatable="false">0</string>
    <string name="support_text_patreon" translatable="false">Подержать в Patreon</string>
    <string name="support_text_buy_me_a_coffee" translatable="false">Угостить меня кофейком</string>
    <string name="crowd_in_text" translatable="false">Услуги перевода Crowdin</string>
    <string name="crowd_in_link" translatable="false">https://crowdin.com/project/nexnotes</string>
    <string name="source_code_link" translatable="false">https://github.com/Swatian/nexnotes</string>
	
    <string name="settings_biometric_header">Биометрический замок</string>
    <string name="created_with">Создано %s</string>
    <string name="updated_with">Обновлен %s</string>
    <string name="nothing_found">Здесь пусто</string>
    <string name="delete_note_dialog_message">Вы точно хотите удалить эту записку?</string>
    <plurals name="note_delete_message">
        <item quantity="one">Записка удалена успешно</item>
        <item quantity="other">Записки удалены успешно</item>
    </plurals>
    <string name="all_good">Вы все сделали</string>
    <string name="delete_notes">Удалить все записи</string>
    <string name="note_content_hint">Начните вести свои записи здесь…</string>
    <string name="delete_all_notes_dialog_message">Это удалит все ваши записки. Вернуть это действие нельзя.</string>
    <string name="delete_topic_dialog_message">Вы хотите удалить задание. Нажмите Удалить для продолжения.</string>
    <string name="delete_topic_message">Задание удалена успешно</string>
    <string name="topic_created">Задание создано</string>
    <string name="biometric_auth_title">Аутентификация по биометрии</string>
    <string name="biometric_auth_sub_title">Разблокировка с ваших биометрических данных</string>
    <string name="settings_saved">Настройки сохранены</string>
    <string name="enroll_biometric">Внести биометрические данные в настройках телефона</string>
    <string name="biometric_not_supported">На этом устройстве нет биометрических функций</string>
    <string name="biometric_not_available">Биометрические функции пока недоступны</string>
    <string name="settings_language_selector_dialog_title">Выбор языка</string>
    <string name="source_code">Исходный код</string>
    
    
    <string name="generic_error">Что-то пошло не так</string>
    <string name="browser_open_failed">Не найдено приложение для открытия этой ссылки</string>
    <string name="topic_exists">Задание уже есть</string>
    <string name="topic_min_characters">Задание должна содержать не менее 2-х символов</string>
    
    	
    
    <string name="notes">Записки</string>
    <string name="topics">Задания</string>
    <string name="topic">Задание</string>
    <string name="settings">Настройки</string>
    <string name="notifications">Дать знать</string>
    <string name="app">Приложение</string>
    <string name="generic_img_copy">картинка</string>
    <string name="cancel">Отмена</string>
    <string name="update">Обновить</string>
    <string name="add">Добавлять</string>
    <string name="new_text">Новая</string>
    <string name="error">ошибка</string>
    <string name="ok">ОК</string>
    <string name="proceed">Продолжить</string>
    <string name="theme">Тема</string>
    <string name="language">Язык</string>
    <string name="active">Активно</string>
    <string name="delete">Удалить</string>
    <string name="accounts">Кол-во</string>
    <string name="edit">Правка</string>
    <string name="remove">Удалить</string>
    <string name="name">Имя</string>
    <string name="about">Инфо о ПО</string>
    <string name="website">Оф. веб-сайт</string>
    <string name="system">Системный</string>
    <string name="search">Поиск</string>
    <string name="display">Отобразить</string>
    <string name="appearance">Облик</string>
    <string name="translation">Перевод</string>
    <string name="security">Охрана</string>
    <string name="version">Версия</string>
    <string name="links">Ссылки</string>
    <string name="close">Закрыть</string>
    <string name="description">Описание</string>
    <string name="create">Создать</string>
    <string name="database">База данных</string>
    <string name="title">Заголовок (обязательно)</string>
    <string name="general">В целом</string>
    <string name="save">Сохранить</string>
    
</resources>

**Comment by mmarif4u** [comment]
Translations are done through Crowdin only.
